# Generated by Django 5.2.3 on 2025-07-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a10_topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('daydate', models.DateField()),
                ('travelstart', models.TimeField(null=True)),
                ('travelend', models.TimeField(null=True)),
                ('workstart', models.TimeField(null=True)),
                ('workend', models.TimeField(null=True)),
                ('fk_code_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a10_topics.worktypes_db')),
                ('fk_machine_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a10_topics.machinedata_db')),
                ('fk_work_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a10_topics.workdata_db')),
            ],
        ),
    ]
