# Generated by Django 5.2.3 on 2025-07-07 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineData_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTypes_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkData_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(max_length=64, null=True)),
                ('workType_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a10_topics.worktypes_db')),
            ],
        ),
    ]
